### ISSUE TITLE
Application crash on start

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#149]
As seen in cozy/cozy-proxy#150
Here are the logs:

```
[TypeError: Cannot read property 'length' of undefined]
TypeError: Cannot read property 'length' of undefined
    at Object.async.each (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:120:17)
    at /usr/local/cozy/apps/photos/build/server/controllers/album.js:40:18
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:32:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:251:21
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:575:34
    at /usr/local/cozy/apps/photos/build/server/models/album.js:57:16
    at /usr/local/cozy/apps/photos/node_modules/async/lib/async.js:254:17
    at done (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:129:15)
```

It's probably because we don't handle the error case here https://github.com/cozy/cozy-photos/blob/master/server/controllers/album.coffee#L24

**Comment by poupotte** [comment]
Thanks @clochix.
