### ISSUE TITLE
Server crash on application startup

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#159]
Related to GPS patch:

```
[TypeError: Cannot read property 'raw' of undefined]
TypeError: Cannot read property 'raw' of undefined
    at Photo.module.exports.Photo.extractGpsFromBinary (/usr/local/cozy/apps/photos/build/server/models/photo.js:65:21)
    at /usr/local/cozy/apps/photos/build/server/models/photo.js:55:24
    at iterate (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:149:13)
    at Object._onImmediate (/usr/local/cozy/apps/photos/node_modules/async/lib/async.js:160:25)
    at processImmediate [as _immediateCallback] (timers.js:354:15)
```

**Comment by poupotte** [comment]
Thanks @clochix .
