### ISSUE TITLE
Server crash when trying to share an album

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#168]
Here are the logs:

```
[TypeError: Cannot read property 'name' of undefined]
TypeError: Cannot read property 'name' of undefined
    at /usr/local/cozy/apps/photos/build/server/controllers/sharing.js:38:33
    at /usr/local/cozy/apps/photos/build/server/controllers/sharing.js:17:14
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/model.js:240:16
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/model.js:198:20
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/cozymodel.js:252:18
    at parseBody (/usr/local/cozy/apps/photos/node_modules/cozydb/node_modules/request-json-light/main.js:75:10)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/photos/node_modules/cozydb/node_modules/request-json-light/main.js:109:14)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

**Comment by clochix** [comment]
The root cause of the error seems to be a CouchDB timeout (maybe related to email indexing), but the error is not catched.
