### ISSUE TITLE
Error 504: Gateway Time-out

### ISSUE THREAD

**Issue by kosssi** [cozy/cozy-photos-v2#174]
After installing the application, I have this logs:

```
[2015-11-30 07:11:16:622] info - americano | Configuration for production loaded."
cozy-photos server is listening on port 9119...
{ [Error: Error code 404 - {"error":"Not Found"}] status: 404 }
[ReferenceError: callbabk is not defined]
ReferenceError: callbabk is not defined
    at LaterStream.callback (/usr/local/cozy/apps/photos/build/server/models/photo.js:77:18)
    at LaterStream.module.exports.LaterStream._onStreamingDone (/usr/local/cozy/apps/photos/node_modules/cozydb/lib/utils/later_stream.js:42:21)
    at LaterStream._onStreamingDone (/usr/local/cozy/apps/photos/node_modules/cozydb/lib/utils/later_stream.js:4:61)
    at /usr/local/cozy/apps/photos/node_modules/cozydb/lib/utils/later_stream.js:75:26
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/photos/node_modules/cozydb/lib/utils/later_stream.js:19:41)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

Thanks,

**Comment by clochix** [comment]
Thanks for reporting @kosssi 
I think this has been fixed a few days ago, and the fox will be available as soon as the new version of photo is published. Stay tuned !

**Comment by kosssi** [comment]
Thanks, I close when the new version is ok ;)

**Comment by clochix** [comment]
@kosssi can we close this one ?
