### ISSUE TITLE
TypeError: path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-photos-v2#175]
```
TypeError: path must be absolute or specify root to res.sendFile
    at ServerResponse.sendFile (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/response.js:389:11)
    at /usr/local/cozy/apps/photos/build/server/controllers/photo.js:236:18
    at Object.module.exports.checkPermissionsPhoto (/usr/local/cozy/apps/photos/build/server/controllers/sharing.js:110:12)
    at doPipe (/usr/local/cozy/apps/photos/build/server/controllers/photo.js:194:18)
    at module.exports.thumb (/usr/local/cozy/apps/photos/build/server/controllers/photo.js:248:10)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/cozy/apps/photos/node_modules/americano/node_modules/express/lib/router/index.js:267:22
```

**Comment by clochix** [comment]
This error were thrown when the server is unable to access the photo (error in DS). The path of the error photo was wrong.

**Comment by poupotte** [comment]
Thanks @clochix
